export default {
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CONFIRM_USER: 'CONFIRM_USER',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_EMAIL_PASSWORD: 'VERIFY_EMAIL_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
}
